spring:
  datasource:
    url: jdbc:h2:~/Book_rant
    username: master
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.sql: warn
    org.hibernate.type: trace